/**
 * Dynamic Lucide Icon Resolver
 * Resolves a kebab-case icon name (e.g. "hard-drive") to its Lucide React component.
 * Uses a curated map of common icons instead of importing all 1500+ icons.
 */
import {
  Server,
  HardDrive,
  ShieldCheck,
  Lock,
  Activity,
  Layers,
  Cloud,
  Brain,
  Laptop,
  Cpu,
  Database,
  Monitor,
  Shield,
  ShieldAlert,
  ShieldOff,
  Key,
  KeyRound,
  LockKeyhole,
  Fingerprint,
  ScanEye,
  Scan,
  Bug,
  CloudCog,
  CloudDownload,
  CloudUpload,
  Network,
  Wifi,
  Globe,
  Router,
  Cable,
  SatelliteDish,
  BarChart3,
  LineChart,
  PieChart,
  TrendingUp,
  Gauge,
  BrainCircuit,
  Bot,
  Sparkles,
  Zap,
  Settings,
  Settings2,
  Wrench,
  Hammer,
  Cog,
  SlidersHorizontal,
  Headphones,
  Headset,
  Phone,
  PhoneCall,
  Mail,
  MessageCircle,
  MessageSquare,
  LifeBuoy,
  Users,
  User,
  UserCheck,
  UserCog,
  Building2,
  Briefcase,
  Handshake,
  Award,
  Trophy,
  Target,
  File,
  FileText,
  FileCheck,
  Folder,
  FolderOpen,
  ClipboardList,
  ArrowRight,
  ArrowUpRight,
  ChevronRight,
  Move,
  RefreshCw,
  RotateCw,
  CheckCircle,
  Check,
  XCircle,
  AlertTriangle,
  Info,
  Bell,
  Clock,
  Timer,
  Calendar,
  Star,
  Heart,
  Bookmark,
  Link,
  ExternalLink,
  Download,
  Upload,
  Search,
  Eye,
  Package,
  Truck,
  Rocket,
  Flame,
  Lightbulb,
  Plug,
  Power,
  BatteryCharging,
  Code,
  Terminal,
  GitBranch,
  Webhook,
  Blocks,
  Workflow,
  Shuffle,
  MapPin,
  Image,
  Video,
  Play,
  SquareKanban,
  type LucideIcon,
} from "lucide-react";

/**
 * Map of kebab-case icon names to their Lucide React components.
 * This map allows dynamic resolution of icons from API data.
 */
const ICON_MAP: Record<string, LucideIcon> = {
  infraestrutura: Server,
  armazenamento: HardDrive,
  "protecao-de-dados": ShieldCheck,
  seguranca: Lock,
  observability: Activity,
  virtualizacao: Layers,
  endpoints: Laptop,
  "inteligencia-artificial": Brain,
  server: Server,
  "hard-drive": HardDrive,
  "shield-check": ShieldCheck,
  lock: Lock,
  activity: Activity,
  layers: Layers,
  cloud: Cloud,
  brain: Brain,
  laptop: Laptop,
  cpu: Cpu,
  database: Database,
  monitor: Monitor,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-off": ShieldOff,
  key: Key,
  "key-round": KeyRound,
  "lock-keyhole": LockKeyhole,
  fingerprint: Fingerprint,
  "scan-eye": ScanEye,
  scan: Scan,
  bug: Bug,
  "cloud-cog": CloudCog,
  "cloud-download": CloudDownload,
  "cloud-upload": CloudUpload,
  network: Network,
  wifi: Wifi,
  globe: Globe,
  router: Router,
  cable: Cable,
  "satellite-dish": SatelliteDish,
  "bar-chart-3": BarChart3,
  "line-chart": LineChart,
  "pie-chart": PieChart,
  "trending-up": TrendingUp,
  gauge: Gauge,
  "brain-circuit": BrainCircuit,
  bot: Bot,
  sparkles: Sparkles,
  zap: Zap,
  settings: Settings,
  "settings-2": Settings2,
  wrench: Wrench,
  hammer: Hammer,
  cog: Cog,
  "sliders-horizontal": SlidersHorizontal,
  headphones: Headphones,
  headset: Headset,
  phone: Phone,
  "phone-call": PhoneCall,
  mail: Mail,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "life-buoy": LifeBuoy,
  users: Users,
  user: User,
  "user-check": UserCheck,
  "user-cog": UserCog,
  "building-2": Building2,
  briefcase: Briefcase,
  handshake: Handshake,
  award: Award,
  trophy: Trophy,
  target: Target,
  file: File,
  "file-text": FileText,
  "file-check": FileCheck,
  folder: Folder,
  "folder-open": FolderOpen,
  "clipboard-list": ClipboardList,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "chevron-right": ChevronRight,
  move: Move,
  "refresh-cw": RefreshCw,
  "rotate-cw": RotateCw,
  "check-circle": CheckCircle,
  check: Check,
  "x-circle": XCircle,
  "alert-triangle": AlertTriangle,
  info: Info,
  bell: Bell,
  clock: Clock,
  timer: Timer,
  calendar: Calendar,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  link: Link,
  "external-link": ExternalLink,
  download: Download,
  upload: Upload,
  search: Search,
  eye: Eye,
  package: Package,
  truck: Truck,
  rocket: Rocket,
  flame: Flame,
  lightbulb: Lightbulb,
  plug: Plug,
  power: Power,
  "battery-charging": BatteryCharging,
  code: Code,
  terminal: Terminal,
  "git-branch": GitBranch,
  webhook: Webhook,
  blocks: Blocks,
  workflow: Workflow,
  shuffle: Shuffle,
  "map-pin": MapPin,
  image: Image,
  video: Video,
  play: Play,
  "square-kanban": SquareKanban,
};

/**
 * Resolves a kebab-case Lucide icon name to its React component.
 * Returns the fallback icon (Server) if the name is not found.
 */
export function resolveLucideIcon(name?: string, fallback: LucideIcon = Server): LucideIcon {
  if (!name) return fallback;
  return ICON_MAP[name] || fallback;
}

export { ICON_MAP };
